// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.implementation.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The CreateVectorStoreFileBatchRequest model.
 */

public final class CreateVectorStoreFileBatchRequest implements JsonSerializable<CreateVectorStoreFileBatchRequest> {

    /*
     * A list of File IDs that the vector store should use. Useful for tools like `file_search` that can access files.
     */

    private final List<String> fileIds;

    /**
     * Creates an instance of CreateVectorStoreFileBatchRequest class.
     *
     * @param fileIds the fileIds value to set.
     */

    public CreateVectorStoreFileBatchRequest(List<String> fileIds) {
        this.fileIds = fileIds;
    }

    /**
     * Get the fileIds property: A list of File IDs that the vector store should use. Useful for tools like
     * `file_search` that can access files.
     *
     * @return the fileIds value.
     */

    public List<String> getFileIds() {
        return this.fileIds;
    }

    /**
     * {@inheritDoc}
     */

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("file_ids", this.fileIds, (writer, element) -> writer.writeString(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of CreateVectorStoreFileBatchRequest from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of CreateVectorStoreFileBatchRequest if the JsonReader was pointing to an instance of it, or
     * null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the CreateVectorStoreFileBatchRequest.
     */

    public static CreateVectorStoreFileBatchRequest fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            List<String> fileIds = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("file_ids".equals(fieldName)) {
                    fileIds = reader.readArray(reader1 -> reader1.getString());
                } else {
                    reader.skipChildren();
                }
            }
            return new CreateVectorStoreFileBatchRequest(fileIds);
        });
    }
}
