// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;

import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
/**
 * Possible API response formats.
 */
public final class ApiResponseFormat implements ExpandableEnum<ApiResponseFormat> {
    private static final Map<String, ApiResponseFormat> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private ApiResponseFormat(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public ApiResponseFormat getValue() {
        return ApiResponseFormat.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link ApiResponseFormat} values.
     *
     * @return The known {@link ApiResponseFormat} values.
     */
    public static Collection<ApiResponseFormat> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link ApiResponseFormat} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link ApiResponseFormat} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static ApiResponseFormat fromString(String name) {
        if (name == null) {
            return null;
        }

        ApiResponseFormat exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, ApiResponseFormat::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof ApiResponseFormat)) {
            return false;
        }

        ApiResponseFormat other = (ApiResponseFormat) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * `text` format should be used for requests involving any sort of ToolCall.
     */
    
    public static final ApiResponseFormat TEXT = fromString("text");

    /**
     * Using `json_object` format will limit the usage of ToolCall to only functions.
     */
    
    public static final ApiResponseFormat JSON_OBJECT = fromString("json_object");
}
