// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Available tool types for assistants named tools.
 */
public final class AssistantsNamedToolChoiceType implements ExpandableEnum<AssistantsNamedToolChoiceType> {
    private static final Map<String, AssistantsNamedToolChoiceType> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private AssistantsNamedToolChoiceType(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public AssistantsNamedToolChoiceType getValue() {
        return AssistantsNamedToolChoiceType.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link AssistantsNamedToolChoiceType} values.
     *
     * @return The known {@link AssistantsNamedToolChoiceType} values.
     */
    public static Collection<AssistantsNamedToolChoiceType> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link AssistantsNamedToolChoiceType} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link AssistantsNamedToolChoiceType} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static AssistantsNamedToolChoiceType fromString(String name) {
        if (name == null) {
            return null;
        }

        AssistantsNamedToolChoiceType exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, AssistantsNamedToolChoiceType::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof AssistantsNamedToolChoiceType)) {
            return false;
        }

        AssistantsNamedToolChoiceType other = (AssistantsNamedToolChoiceType) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }
    /**
     * Tool type `function`.
     */

    public static final AssistantsNamedToolChoiceType FUNCTION = fromString("function");

    /**
     * Tool type `code_interpreter`.
     */

    public static final AssistantsNamedToolChoiceType CODE_INTERPRETER = fromString("code_interpreter");

    /**
     * Tool type `file_search`.
     */

    public static final AssistantsNamedToolChoiceType FILE_SEARCH = fromString("file_search");
    
}
