// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;

import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * Specifies a tool the model should use. Use to force the model to call a specific tool.
 */

public final class AssistantsNamedToolChoice implements JsonSerializable<AssistantsNamedToolChoice> {

    /*
     * the type of tool. If type is `function`, the function name must be set.
     */

    private final AssistantsNamedToolChoiceType type;

    /*
     * The name of the function to call
     */

    private FunctionName function;

    /**
     * Creates an instance of AssistantsNamedToolChoice class.
     *
     * @param type the type value to set.
     */

    public AssistantsNamedToolChoice(AssistantsNamedToolChoiceType type) {
        this.type = type;
    }

    /**
     * Get the type property: the type of tool. If type is `function`, the function name must be set.
     *
     * @return the type value.
     */

    public AssistantsNamedToolChoiceType getType() {
        return this.type;
    }

    /**
     * Get the function property: The name of the function to call.
     *
     * @return the function value.
     */

    public FunctionName getFunction() {
        return this.function;
    }

    /**
     * Set the function property: The name of the function to call.
     *
     * @param function the function value to set.
     * @return the AssistantsNamedToolChoice object itself.
     */

    public AssistantsNamedToolChoice setFunction(FunctionName function) {
        this.function = function;
        return this;
    }

    /**
     * {@inheritDoc}
     */

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", this.type == null ? null : this.type.toString());
        jsonWriter.writeJsonField("function", this.function);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of AssistantsNamedToolChoice from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of AssistantsNamedToolChoice if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the AssistantsNamedToolChoice.
     */

    public static AssistantsNamedToolChoice fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            AssistantsNamedToolChoiceType type = null;
            FunctionName function = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("type".equals(fieldName)) {
                    type = AssistantsNamedToolChoiceType.fromString(reader.getString());
                } else if ("function".equals(fieldName)) {
                    function = FunctionName.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }
            AssistantsNamedToolChoice deserializedAssistantsNamedToolChoice = new AssistantsNamedToolChoice(type);
            deserializedAssistantsNamedToolChoice.function = function;
            return deserializedAssistantsNamedToolChoice;
        });
    }
}
