// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.util.ExpandableEnum;
import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Represents the mode in which the model will handle the return format of a tool call.
 */
public final class AssistantsApiResponseFormatMode
    implements ExpandableEnum<AssistantsApiResponseFormatMode> {
    private static final Map<String, AssistantsApiResponseFormatMode> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private AssistantsApiResponseFormatMode(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public AssistantsApiResponseFormatMode getValue() {
        return AssistantsApiResponseFormatMode.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link AssistantsApiResponseFormatMode} values.
     *
     * @return The known {@link AssistantsApiResponseFormatMode} values.
     */
    public static Collection<AssistantsApiResponseFormatMode> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link AssistantsApiResponseFormatMode} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link AssistantsApiResponseFormatMode} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static AssistantsApiResponseFormatMode fromString(String name) {
        if (name == null) {
            return null;
        }

        AssistantsApiResponseFormatMode exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, AssistantsApiResponseFormatMode::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof AssistantsApiResponseFormatMode)) {
            return false;
        }

        AssistantsApiResponseFormatMode other = (AssistantsApiResponseFormatMode) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }
    /**
     * Default value. Let the model handle the return format.
     */

    public static final AssistantsApiResponseFormatMode AUTO = fromString("auto");

    /**
     * Setting the value to `none`, will result in a 400 Bad request.
     */

    public static final AssistantsApiResponseFormatMode NONE = fromString("none");
}
