// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The reason why the run is incomplete. This will point to which specific token limit was reached over the course of
 * the run.
 */
public final class IncompleteRunDetails implements ExpandableEnum<IncompleteRunDetails> {
    private static final Map<String, IncompleteRunDetails> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private IncompleteRunDetails(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public IncompleteRunDetails getValue() {
        return IncompleteRunDetails.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link IncompleteRunDetails} values.
     *
     * @return The known {@link IncompleteRunDetails} values.
     */
    public static Collection<IncompleteRunDetails> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link IncompleteRunDetails} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link IncompleteRunDetails} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static IncompleteRunDetails fromString(String name) {
        if (name == null) {
            return null;
        }

        IncompleteRunDetails exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, IncompleteRunDetails::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof IncompleteRunDetails)) {
            return false;
        }

        IncompleteRunDetails other = (IncompleteRunDetails) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }
    /**
     * Maximum completion tokens exceeded.
     */
    
    public static final IncompleteRunDetails MAX_COMPLETION_TOKENS = fromString("max_completion_tokens");

    /**
     * Maximum prompt tokens exceeded.
     */
    
    public static final IncompleteRunDetails MAX_PROMPT_TOKENS = fromString("max_prompt_tokens");
}
