// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.util.ExpandableEnum;

import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The available sorting options when requesting a list of response objects.
 */
public final class ListSortOrder implements ExpandableEnum<ListSortOrder> {
    private static final Map<String, ListSortOrder> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private ListSortOrder(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public ListSortOrder getValue() {
        return ListSortOrder.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link ListSortOrder} values.
     *
     * @return The known {@link ListSortOrder} values.
     */
    public static Collection<ListSortOrder> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link ListSortOrder} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link ListSortOrder} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static ListSortOrder fromString(String name) {
        if (name == null) {
            return null;
        }

        ListSortOrder exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, ListSortOrder::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof ListSortOrder)) {
            return false;
        }

        ListSortOrder other = (ListSortOrder) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * Specifies an ascending sort order.
     */
    
    public static final ListSortOrder ASCENDING = fromString("asc");

    /**
     * Specifies a descending sort order.
     */
    
    public static final ListSortOrder DESCENDING = fromString("desc");
}
