// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * Represents the 'image_file' payload within streaming image file content.
 */

public final class MessageDeltaImageFileContentObject implements JsonSerializable<MessageDeltaImageFileContentObject> {

    /*
     * The file ID of the image in the message content.
     */
    
    private String fileId;

    /**
     * Creates an instance of MessageDeltaImageFileContentObject class.
     */
    
    private MessageDeltaImageFileContentObject() {
    }

    /**
     * Get the fileId property: The file ID of the image in the message content.
     *
     * @return the fileId value.
     */
    
    public String getFileId() {
        return this.fileId;
    }

    /**
     * {@inheritDoc}
     */
    
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("file_id", this.fileId);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of MessageDeltaImageFileContentObject from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of MessageDeltaImageFileContentObject if the JsonReader was pointing to an instance of it, or
     * null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the MessageDeltaImageFileContentObject.
     */
    
    public static MessageDeltaImageFileContentObject fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            MessageDeltaImageFileContentObject deserializedMessageDeltaImageFileContentObject
                = new MessageDeltaImageFileContentObject();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("file_id".equals(fieldName)) {
                    deserializedMessageDeltaImageFileContentObject.fileId = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return deserializedMessageDeltaImageFileContentObject;
        });
    }
}
