// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * Represents the data of a streamed text content part within a streaming message delta chunk.
 */

public final class MessageDeltaTextContent implements JsonSerializable<MessageDeltaTextContent> {

    /*
     * The data that makes up the text.
     */

    private String value;

    /*
     * Annotations for the text.
     */

    private List<MessageDeltaTextAnnotation> annotations;

    /**
     * Creates an instance of MessageDeltaTextContent class.
     */

    private MessageDeltaTextContent() {
    }

    /**
     * Get the value property: The data that makes up the text.
     *
     * @return the value value.
     */

    public String getValue() {
        return this.value;
    }

    /**
     * Get the annotations property: Annotations for the text.
     *
     * @return the annotations value.
     */

    public List<MessageDeltaTextAnnotation> getAnnotations() {
        return this.annotations;
    }

    /**
     * {@inheritDoc}
     */

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("value", this.value);
        jsonWriter.writeArrayField("annotations", this.annotations, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of MessageDeltaTextContent from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of MessageDeltaTextContent if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the MessageDeltaTextContent.
     */

    public static MessageDeltaTextContent fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            MessageDeltaTextContent deserializedMessageDeltaTextContent = new MessageDeltaTextContent();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("value".equals(fieldName)) {
                    deserializedMessageDeltaTextContent.value = reader.getString();
                } else if ("annotations".equals(fieldName)) {
                    List<MessageDeltaTextAnnotation> annotations
                        = reader.readArray(reader1 -> MessageDeltaTextAnnotation.fromJson(reader1));
                    deserializedMessageDeltaTextContent.annotations = annotations;
                } else {
                    reader.skipChildren();
                }
            }
            return deserializedMessageDeltaTextContent;
        });
    }
}
