// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * Represents a streamed file citation applied to a streaming text content part.
 */

public final class MessageDeltaTextFileCitationAnnotationObject extends MessageDeltaTextAnnotation {

    /*
     * The type of the text content annotation.
     */

    private String type = "file_citation";

    /*
     * The file citation information.
     */

    private MessageDeltaTextFileCitationAnnotation fileCitation;

    /*
     * The start index of this annotation in the content text.
     */

    private Integer startIndex;

    /*
     * The end index of this annotation in the content text.
     */

    private Integer endIndex;

    /**
     * Creates an instance of MessageDeltaTextFileCitationAnnotationObject class.
     *
     * @param index the index value to set.
     */

    private MessageDeltaTextFileCitationAnnotationObject(int index) {
        super(index);
    }

    /**
     * Get the type property: The type of the text content annotation.
     *
     * @return the type value.
     */

    @Override
    public String getType() {
        return this.type;
    }

    /**
     * Get the fileCitation property: The file citation information.
     *
     * @return the fileCitation value.
     */

    public MessageDeltaTextFileCitationAnnotation getFileCitation() {
        return this.fileCitation;
    }

    /**
     * Get the startIndex property: The start index of this annotation in the content text.
     *
     * @return the startIndex value.
     */

    public Integer getStartIndex() {
        return this.startIndex;
    }

    /**
     * Get the endIndex property: The end index of this annotation in the content text.
     *
     * @return the endIndex value.
     */

    public Integer getEndIndex() {
        return this.endIndex;
    }

    /**
     * {@inheritDoc}
     */

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeIntField("index", getIndex());
        jsonWriter.writeStringField("type", this.type);
        jsonWriter.writeJsonField("file_citation", this.fileCitation);
        jsonWriter.writeStringField("text", this.text);
        jsonWriter.writeNumberField("start_index", this.startIndex);
        jsonWriter.writeNumberField("end_index", this.endIndex);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of MessageDeltaTextFileCitationAnnotationObject from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of MessageDeltaTextFileCitationAnnotationObject if the JsonReader was pointing to an instance
     * of it, or null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the MessageDeltaTextFileCitationAnnotationObject.
     */

    public static MessageDeltaTextFileCitationAnnotationObject fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            int index = 0;
            String type = "file_citation";
            MessageDeltaTextFileCitationAnnotation fileCitation = null;
            String text = null;
            Integer startIndex = null;
            Integer endIndex = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("index".equals(fieldName)) {
                    index = reader.getInt();
                } else if ("type".equals(fieldName)) {
                    type = reader.getString();
                } else if ("file_citation".equals(fieldName)) {
                    fileCitation = MessageDeltaTextFileCitationAnnotation.fromJson(reader);
                } else if ("text".equals(fieldName)) {
                    text = reader.getString();
                } else if ("start_index".equals(fieldName)) {
                    startIndex = reader.getNullable(JsonReader::getInt);
                } else if ("end_index".equals(fieldName)) {
                    endIndex = reader.getNullable(JsonReader::getInt);
                } else {
                    reader.skipChildren();
                }
            }
            MessageDeltaTextFileCitationAnnotationObject deserializedMessageDeltaTextFileCitationAnnotationObject
                = new MessageDeltaTextFileCitationAnnotationObject(index);
            deserializedMessageDeltaTextFileCitationAnnotationObject.type = type;
            deserializedMessageDeltaTextFileCitationAnnotationObject.fileCitation = fileCitation;
            deserializedMessageDeltaTextFileCitationAnnotationObject.text = text;
            deserializedMessageDeltaTextFileCitationAnnotationObject.startIndex = startIndex;
            deserializedMessageDeltaTextFileCitationAnnotationObject.endIndex = endIndex;
            return deserializedMessageDeltaTextFileCitationAnnotationObject;
        });
    }

    /*
     * The text in the message content that needs to be replaced
     */

    private String text;

    /**
     * Get the text property: The text in the message content that needs to be replaced.
     *
     * @return the text value.
     */

    public String getText() {
        return this.text;
    }
}
