// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * An image reference, as represented in thread message content.
 */

public final class MessageImageFileDetails implements JsonSerializable<MessageImageFileDetails> {

    /*
     * The ID for the file associated with this image.
     */
    
    private final String fileId;

    /**
     * Get the fileId property: The ID for the file associated with this image.
     *
     * @return the fileId value.
     */
    
    public String getFileId() {
        return this.fileId;
    }

    /**
     * Creates an instance of MessageImageFileDetails class.
     *
     * @param fileId the fileId value to set.
     */
    
    public MessageImageFileDetails(String fileId) {
        this.fileId = fileId;
    }

    /**
     * {@inheritDoc}
     */
    
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("file_id", this.fileId);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of MessageImageFileDetails from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of MessageImageFileDetails if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the MessageImageFileDetails.
     */
    
    public static MessageImageFileDetails fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String fileId = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("file_id".equals(fieldName)) {
                    fileId = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return new MessageImageFileDetails(fileId);
        });
    }
}
