// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;

import io.clientcore.core.util.ExpandableEnum;
import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The possible values for roles attributed to messages in a thread.
 */
public final class MessageRole implements ExpandableEnum<MessageRole> {
    private static final Map<String, MessageRole> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private MessageRole(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public MessageRole getValue() {
        return MessageRole.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link MessageRole} values.
     *
     * @return The known {@link MessageRole} values.
     */
    public static Collection<MessageRole> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link MessageRole} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link MessageRole} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static MessageRole fromString(String name) {
        if (name == null) {
            return null;
        }

        MessageRole exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, MessageRole::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof MessageRole)) {
            return false;
        }

        MessageRole other = (MessageRole) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }
    
    /**
     * The role representing the end-user.
     */
    
    public static final MessageRole USER = fromString("user");

    /**
     * The role representing the assistant.
     */
    
    public static final MessageRole ASSISTANT = fromString("assistant");
}
