// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;



import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The possible execution status values for a thread message.
 */
public final class MessageStatus implements ExpandableEnum<MessageStatus> {
    private static final Map<String, MessageStatus> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private MessageStatus(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public MessageStatus getValue() {
        return MessageStatus.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link MessageStatus} values.
     *
     * @return The known {@link MessageStatus} values.
     */
    public static Collection<MessageStatus> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link MessageStatus} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link MessageStatus} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static MessageStatus fromString(String name) {
        if (name == null) {
            return null;
        }

        MessageStatus exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, MessageStatus::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof MessageStatus)) {
            return false;
        }

        MessageStatus other = (MessageStatus) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * A run is currently creating this message.
     */

    public static final MessageStatus IN_PROGRESS = fromString("in_progress");

    /**
     * This message is incomplete. See incomplete_details for more information.
     */

    public static final MessageStatus INCOMPLETE = fromString("incomplete");

    /**
     * This message was successfully completed by a run.
     */

    public static final MessageStatus COMPLETED = fromString("completed");

}
