// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * A representation of a requested call to a function tool, needed by the model to continue evaluation of a run.
 */

public final class RequiredFunctionToolCall extends RequiredToolCall {

    /*
     * Detailed information about the function to be executed by the tool that includes name and arguments.
     */

    private final RequiredFunctionToolCallDetails function;

    /**
     * Get the function property: Detailed information about the function to be executed by the tool that includes name
     * and arguments.
     *
     * @return the function value.
     */

    public RequiredFunctionToolCallDetails getFunction() {
        return this.function;
    }

    /**
     * Creates an instance of RequiredFunctionToolCall class.
     *
     * @param id the id value to set.
     * @param function the function value to set.
     */

    private RequiredFunctionToolCall(String id, RequiredFunctionToolCallDetails function) {
        super(id);
        this.function = function;
    }

    /**
     * {@inheritDoc}
     */

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("id", getId());
        jsonWriter.writeJsonField("function", this.function);
        jsonWriter.writeStringField("type", this.type);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RequiredFunctionToolCall from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of RequiredFunctionToolCall if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the RequiredFunctionToolCall.
     */

    public static RequiredFunctionToolCall fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String id = null;
            RequiredFunctionToolCallDetails function = null;
            String type = "function";
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("id".equals(fieldName)) {
                    id = reader.getString();
                } else if ("function".equals(fieldName)) {
                    function = RequiredFunctionToolCallDetails.fromJson(reader);
                } else if ("type".equals(fieldName)) {
                    type = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            RequiredFunctionToolCall deserializedRequiredFunctionToolCall = new RequiredFunctionToolCall(id, function);
            deserializedRequiredFunctionToolCall.type = type;
            return deserializedRequiredFunctionToolCall;
        });
    }

    /*
     * The object type for the required tool call.
     */

    private String type = "function";

    /**
     * Get the type property: The object type for the required tool call.
     *
     * @return the type value.
     */

    @Override
    public String getType() {
        return this.type;
    }
}
