// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * Represents the data within a streaming run step message creation response object.
 */

public final class RunStepDeltaMessageCreationObject implements JsonSerializable<RunStepDeltaMessageCreationObject> {

    /*
     * The ID of the newly-created message.
     */
    
    private String messageId;

    /**
     * Creates an instance of RunStepDeltaMessageCreationObject class.
     */
    
    private RunStepDeltaMessageCreationObject() {
    }

    /**
     * Get the messageId property: The ID of the newly-created message.
     *
     * @return the messageId value.
     */
    
    public String getMessageId() {
        return this.messageId;
    }

    /**
     * {@inheritDoc}
     */
    
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("message_id", this.messageId);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RunStepDeltaMessageCreationObject from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of RunStepDeltaMessageCreationObject if the JsonReader was pointing to an instance of it, or
     * null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the RunStepDeltaMessageCreationObject.
     */
    
    public static RunStepDeltaMessageCreationObject fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RunStepDeltaMessageCreationObject deserializedRunStepDeltaMessageCreationObject
                = new RunStepDeltaMessageCreationObject();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("message_id".equals(fieldName)) {
                    deserializedRunStepDeltaMessageCreationObject.messageId = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return deserializedRunStepDeltaMessageCreationObject;
        });
    }
}
