// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Run operation related streaming events.
 */
public final class RunStreamEvent implements ExpandableEnum<RunStreamEvent> {
    private static final Map<String, RunStreamEvent> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private RunStreamEvent(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public RunStreamEvent getValue() {
        return RunStreamEvent.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link RunStreamEvent} values.
     *
     * @return The known {@link RunStreamEvent} values.
     */
    public static Collection<RunStreamEvent> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link RunStreamEvent} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link RunStreamEvent} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static RunStreamEvent fromString(String name) {
        if (name == null) {
            return null;
        }

        RunStreamEvent exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, RunStreamEvent::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof RunStreamEvent)) {
            return false;
        }

        RunStreamEvent other = (RunStreamEvent) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * Event sent when a new run is created. The data of this event is of type ThreadRun.
     */
    
    public static final RunStreamEvent THREAD_RUN_CREATED = fromString("thread.run.created");

    /**
     * Event sent when a run moves to `queued` status. The data of this event is of type ThreadRun.
     */
    
    public static final RunStreamEvent THREAD_RUN_QUEUED = fromString("thread.run.queued");

    /**
     * Event sent when a run moves to `in_progress` status. The data of this event is of type ThreadRun.
     */
    
    public static final RunStreamEvent THREAD_RUN_IN_PROGRESS = fromString("thread.run.in_progress");

    /**
     * Event sent when a run moves to `requires_action` status. The data of this event is of type ThreadRun.
     */
    
    public static final RunStreamEvent THREAD_RUN_REQUIRES_ACTION = fromString("thread.run.requires_action");

    /**
     * Event sent when a run is completed. The data of this event is of type ThreadRun.
     */
    
    public static final RunStreamEvent THREAD_RUN_COMPLETED = fromString("thread.run.completed");

    /**
     * Event sent when a run fails. The data of this event is of type ThreadRun.
     */
    
    public static final RunStreamEvent THREAD_RUN_FAILED = fromString("thread.run.failed");

    /**
     * Event sent when a run moves to `cancelling` status. The data of this event is of type ThreadRun.
     */
    
    public static final RunStreamEvent THREAD_RUN_CANCELLING = fromString("thread.run.cancelling");

    /**
     * Event sent when a run is cancelled. The data of this event is of type ThreadRun.
     */
    
    public static final RunStreamEvent THREAD_RUN_CANCELLED = fromString("thread.run.cancelled");

    /**
     * Event sent when a run is expired. The data of this event is of type ThreadRun.
     */
    
    public static final RunStreamEvent THREAD_RUN_EXPIRED = fromString("thread.run.expired");


}
