// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * The detailed information about the function called by the model.
 */

public final class RunStepFunctionToolCallDetails implements JsonSerializable<RunStepFunctionToolCallDetails> {

    /*
     * The name of the function.
     */
    
    private final String name;

    /*
     * The arguments that the model requires are provided to the named function.
     */
    
    private final String arguments;

    /*
     * The output of the function, only populated for function calls that have already have had their outputs submitted.
     */
    
    private final String output;

    /**
     * Creates an instance of RunStepFunctionToolCallDetails class.
     *
     * @param name the name value to set.
     * @param arguments the arguments value to set.
     * @param output the output value to set.
     */
    
    private RunStepFunctionToolCallDetails(String name, String arguments, String output) {
        this.name = name;
        this.arguments = arguments;
        this.output = output;
    }

    /**
     * Get the name property: The name of the function.
     *
     * @return the name value.
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Get the arguments property: The arguments that the model requires are provided to the named function.
     *
     * @return the arguments value.
     */
    
    public String getArguments() {
        return this.arguments;
    }

    /**
     * Get the output property: The output of the function, only populated for function calls that have already have had
     * their outputs submitted.
     *
     * @return the output value.
     */
    
    public String getOutput() {
        return this.output;
    }

    /**
     * {@inheritDoc}
     */
    
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("name", this.name);
        jsonWriter.writeStringField("arguments", this.arguments);
        jsonWriter.writeStringField("output", this.output);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RunStepFunctionToolCallDetails from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of RunStepFunctionToolCallDetails if the JsonReader was pointing to an instance of it, or
     * null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the RunStepFunctionToolCallDetails.
     */
    
    public static RunStepFunctionToolCallDetails fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String name = null;
            String arguments = null;
            String output = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("name".equals(fieldName)) {
                    name = reader.getString();
                } else if ("arguments".equals(fieldName)) {
                    arguments = reader.getString();
                } else if ("output".equals(fieldName)) {
                    output = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return new RunStepFunctionToolCallDetails(name, arguments, output);
        });
    }
}
