// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * Represents the function data in a streaming run step delta's function tool call.
 */

public final class RunStepDeltaFunction implements JsonSerializable<RunStepDeltaFunction> {

    /*
     * The name of the function.
     */
    
    private String name;

    /*
     * The arguments passed to the function as input.
     */
    
    private String arguments;

    /*
     * The output of the function, null if outputs have not yet been submitted.
     */
    
    private String output;

    /**
     * Get the name property: The name of the function.
     *
     * @return the name value.
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Get the arguments property: The arguments passed to the function as input.
     *
     * @return the arguments value.
     */
    
    public String getArguments() {
        return this.arguments;
    }

    /**
     * Get the output property: The output of the function, null if outputs have not yet been submitted.
     *
     * @return the output value.
     */
    
    public String getOutput() {
        return this.output;
    }

    /**
     * {@inheritDoc}
     */
    
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("name", this.name);
        jsonWriter.writeStringField("arguments", this.arguments);
        jsonWriter.writeStringField("output", this.output);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RunStepDeltaFunction from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of RunStepDeltaFunction if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the RunStepDeltaFunction.
     */
    
    public static RunStepDeltaFunction fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RunStepDeltaFunction deserializedRunStepDeltaFunction = new RunStepDeltaFunction();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("name".equals(fieldName)) {
                    deserializedRunStepDeltaFunction.name = reader.getString();
                } else if ("arguments".equals(fieldName)) {
                    deserializedRunStepDeltaFunction.arguments = reader.getString();
                } else if ("output".equals(fieldName)) {
                    deserializedRunStepDeltaFunction.output = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return deserializedRunStepDeltaFunction;
        });
    }

    /**
     * Creates an instance of RunStepDeltaFunction class.
     */
    
    private RunStepDeltaFunction() {
    }
}
