// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;

import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Possible values for the status of a run step.
 */
public final class RunStepStatus implements ExpandableEnum<RunStepStatus> {
    private static final Map<String, RunStepStatus> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private RunStepStatus(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public RunStepStatus getValue() {
        return RunStepStatus.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link RunStepStatus} values.
     *
     * @return The known {@link RunStepStatus} values.
     */
    public static Collection<RunStepStatus> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link RunStepStatus} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link RunStepStatus} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static RunStepStatus fromString(String name) {
        if (name == null) {
            return null;
        }

        RunStepStatus exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, RunStepStatus::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof RunStepStatus)) {
            return false;
        }

        RunStepStatus other = (RunStepStatus) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * Represents a run step still in progress.
     */

    public static final RunStepStatus IN_PROGRESS = fromString("in_progress");

    /**
     * Represents a run step that was cancelled.
     */

    public static final RunStepStatus CANCELLED = fromString("cancelled");

    /**
     * Represents a run step that failed.
     */

    public static final RunStepStatus FAILED = fromString("failed");

    /**
     * Represents a run step that successfully completed.
     */

    public static final RunStepStatus COMPLETED = fromString("completed");

    /**
     * Represents a run step that expired before otherwise finishing.
     */

    public static final RunStepStatus EXPIRED = fromString("expired");
}
