// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;

import io.clientcore.core.util.ExpandableEnum;
import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The possible types of run steps.
 */
public final class RunStepType implements ExpandableEnum<RunStepType> {
    private static final Map<String, RunStepType> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private RunStepType(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public RunStepType getValue() {
        return RunStepType.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link RunStepType} values.
     *
     * @return The known {@link RunStepType} values.
     */
    public static Collection<RunStepType> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link RunStepType} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link RunStepType} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static RunStepType fromString(String name) {
        if (name == null) {
            return null;
        }

        RunStepType exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, RunStepType::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof RunStepType)) {
            return false;
        }

        RunStepType other = (RunStepType) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }
    /**
     * Represents a run step to create a message.
     */
    
    public static final RunStepType MESSAGE_CREATION = fromString("message_creation");

    /**
     * Represents a run step that calls tools.
     */
    
    public static final RunStepType TOOL_CALLS = fromString("tool_calls");
}
