// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Possible error code values attributable to a failed run step.
 */
public final class RunStepErrorCode implements ExpandableEnum<RunStepErrorCode> {
    private static final Map<String, RunStepErrorCode> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private RunStepErrorCode(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public RunStepErrorCode getValue() {
        return RunStepErrorCode.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link RunStepErrorCode} values.
     *
     * @return The known {@link RunStepErrorCode} values.
     */
    public static Collection<RunStepErrorCode> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link RunStepErrorCode} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link RunStepErrorCode} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static RunStepErrorCode fromString(String name) {
        if (name == null) {
            return null;
        }

        RunStepErrorCode exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, RunStepErrorCode::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof RunStepErrorCode)) {
            return false;
        }

        RunStepErrorCode other = (RunStepErrorCode) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * Represents a server error.
     */

    public static final RunStepErrorCode SERVER_ERROR = fromString("server_error");

    /**
     * Represents an error indicating configured rate limits were exceeded.
     */

    public static final RunStepErrorCode RATE_LIMIT_EXCEEDED = fromString("rate_limit_exceeded");

}
