// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * Represents a message creation within a streaming run step delta.
 */

public final class RunStepDeltaMessageCreation extends RunStepDeltaDetail {

    /*
     * The object type for the run step detail object.
     */

    private String type = "message_creation";

    /*
     * The message creation data.
     */

    private RunStepDeltaMessageCreationObject messageCreation;

    /**
     * Creates an instance of RunStepDeltaMessageCreation class.
     */

    private RunStepDeltaMessageCreation() {
    }

    /**
     * Get the type property: The object type for the run step detail object.
     *
     * @return the type value.
     */

    @Override
    public String getType() {
        return this.type;
    }

    /**
     * Get the messageCreation property: The message creation data.
     *
     * @return the messageCreation value.
     */

    public RunStepDeltaMessageCreationObject getMessageCreation() {
        return this.messageCreation;
    }

    /**
     * {@inheritDoc}
     */

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", this.type);
        jsonWriter.writeJsonField("message_creation", this.messageCreation);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RunStepDeltaMessageCreation from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of RunStepDeltaMessageCreation if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the RunStepDeltaMessageCreation.
     */

    public static RunStepDeltaMessageCreation fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RunStepDeltaMessageCreation deserializedRunStepDeltaMessageCreation = new RunStepDeltaMessageCreation();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("type".equals(fieldName)) {
                    deserializedRunStepDeltaMessageCreation.type = reader.getString();
                } else if ("message_creation".equals(fieldName)) {
                    deserializedRunStepDeltaMessageCreation.messageCreation
                        = RunStepDeltaMessageCreationObject.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }
            return deserializedRunStepDeltaMessageCreation;
        });
    }
}
