// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Thread operation related streaming events.
 */
public final class ThreadStreamEvent implements ExpandableEnum<ThreadStreamEvent> {
    private static final Map<String, ThreadStreamEvent> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private ThreadStreamEvent(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public ThreadStreamEvent getValue() {
        return ThreadStreamEvent.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link ThreadStreamEvent} values.
     *
     * @return The known {@link ThreadStreamEvent} values.
     */
    public static Collection<ThreadStreamEvent> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link ThreadStreamEvent} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link ThreadStreamEvent} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static ThreadStreamEvent fromString(String name) {
        if (name == null) {
            return null;
        }

        ThreadStreamEvent exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, ThreadStreamEvent::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof ThreadStreamEvent)) {
            return false;
        }

        ThreadStreamEvent other = (ThreadStreamEvent) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * Event sent when a new thread is created. The data of this event is of type AssistantThread.
     */

    public static final ThreadStreamEvent THREAD_CREATED = fromString("thread.created");


}
