// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import java.util.Collection;

import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Possible truncation strategies for the thread.
 */
public final class TruncationStrategy implements ExpandableEnum<TruncationStrategy> {
    private static final Map<String, TruncationStrategy> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private TruncationStrategy(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public TruncationStrategy getValue() {
        return TruncationStrategy.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link TruncationStrategy} values.
     *
     * @return The known {@link TruncationStrategy} values.
     */
    public static Collection<TruncationStrategy> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link TruncationStrategy} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link TruncationStrategy} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static TruncationStrategy fromString(String name) {
        if (name == null) {
            return null;
        }

        TruncationStrategy exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, TruncationStrategy::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof TruncationStrategy)) {
            return false;
        }

        TruncationStrategy other = (TruncationStrategy) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * Default value. Messages in the middle of the thread will be dropped to fit the context length of the model.
     */
    
    public static final TruncationStrategy AUTO = fromString("auto");

    /**
     * The thread will truncate to the `lastMessages` count of recent messages.
     */
    
    public static final TruncationStrategy LAST_MESSAGES = fromString("last_messages");
}
