// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;

import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * Request object to update `code_interpreted` tool resources.
 */

public final class UpdateCodeInterpreterToolResourceOptions
    implements JsonSerializable<UpdateCodeInterpreterToolResourceOptions> {

    /*
     * A list of file IDs to override the current list of the assistant.
     */
    
    private List<String> fileIds;

    /**
     * Creates an instance of UpdateCodeInterpreterToolResourceOptions class.
     */
    
    public UpdateCodeInterpreterToolResourceOptions() {
    }

    /**
     * Get the fileIds property: A list of file IDs to override the current list of the assistant.
     *
     * @return the fileIds value.
     */
    
    public List<String> getFileIds() {
        return this.fileIds;
    }

    /**
     * Set the fileIds property: A list of file IDs to override the current list of the assistant.
     *
     * @param fileIds the fileIds value to set.
     * @return the UpdateCodeInterpreterToolResourceOptions object itself.
     */
    
    public UpdateCodeInterpreterToolResourceOptions setFileIds(List<String> fileIds) {
        this.fileIds = fileIds;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("fileIds", this.fileIds, (writer, element) -> writer.writeString(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of UpdateCodeInterpreterToolResourceOptions from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of UpdateCodeInterpreterToolResourceOptions if the JsonReader was pointing to an instance of
     * it, or null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the UpdateCodeInterpreterToolResourceOptions.
     */
    
    public static UpdateCodeInterpreterToolResourceOptions fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            UpdateCodeInterpreterToolResourceOptions deserializedUpdateCodeInterpreterToolResourceOptions
                = new UpdateCodeInterpreterToolResourceOptions();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("fileIds".equals(fieldName)) {
                    List<String> fileIds = reader.readArray(reader1 -> reader1.getString());
                    deserializedUpdateCodeInterpreterToolResourceOptions.fileIds = fileIds;
                } else {
                    reader.skipChildren();
                }
            }
            return deserializedUpdateCodeInterpreterToolResourceOptions;
        });
    }
}
