// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;

import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;


/**
 * Describes the relationship between the days and the expiration of this vector store.
 */
public final class VectorStoreExpirationPolicyAnchor implements ExpandableEnum<VectorStoreExpirationPolicyAnchor> {
    private static final Map<String, VectorStoreExpirationPolicyAnchor> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private VectorStoreExpirationPolicyAnchor(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public VectorStoreExpirationPolicyAnchor getValue() {
        return VectorStoreExpirationPolicyAnchor.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link VectorStoreExpirationPolicyAnchor} values.
     *
     * @return The known {@link VectorStoreExpirationPolicyAnchor} values.
     */
    public static Collection<VectorStoreExpirationPolicyAnchor> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link VectorStoreExpirationPolicyAnchor} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link VectorStoreExpirationPolicyAnchor} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static VectorStoreExpirationPolicyAnchor fromString(String name) {
        if (name == null) {
            return null;
        }

        VectorStoreExpirationPolicyAnchor exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, VectorStoreExpirationPolicyAnchor::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof VectorStoreExpirationPolicyAnchor)) {
            return false;
        }

        VectorStoreExpirationPolicyAnchor other = (VectorStoreExpirationPolicyAnchor) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * The expiration policy is based on the last time the vector store was active.
     */
    
    public static final VectorStoreExpirationPolicyAnchor LAST_ACTIVE_AT = fromString("last_active_at");
}
