// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import java.util.Collection;

import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Error code variants for vector store file processing.
 */
public final class VectorStoreFileErrorCode implements ExpandableEnum<VectorStoreFileErrorCode> {
    private static final Map<String, VectorStoreFileErrorCode> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private VectorStoreFileErrorCode(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public VectorStoreFileErrorCode getValue() {
        return VectorStoreFileErrorCode.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link VectorStoreFileErrorCode} values.
     *
     * @return The known {@link VectorStoreFileErrorCode} values.
     */
    public static Collection<VectorStoreFileErrorCode> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link VectorStoreFileErrorCode} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link VectorStoreFileErrorCode} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static VectorStoreFileErrorCode fromString(String name) {
        if (name == null) {
            return null;
        }

        VectorStoreFileErrorCode exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, VectorStoreFileErrorCode::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof VectorStoreFileErrorCode)) {
            return false;
        }

        VectorStoreFileErrorCode other = (VectorStoreFileErrorCode) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * An internal error occurred.
     */

    public static final VectorStoreFileErrorCode INTERNAL_ERROR = fromString("internal_error");

    /**
     * The file was not found.
     */

    public static final VectorStoreFileErrorCode FILE_NOT_FOUND = fromString("file_not_found");

    /**
     * The file could not be parsed.
     */

    public static final VectorStoreFileErrorCode PARSING_ERROR = fromString("parsing_error");

    /**
     * The file has an unhandled mime type.
     */

    public static final VectorStoreFileErrorCode UNHANDLED_MIME_TYPE = fromString("unhandled_mime_type");
}
