// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Vector store possible status.
 */
public final class VectorStoreStatus implements ExpandableEnum<VectorStoreStatus> {
    private static final Map<String, VectorStoreStatus> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private VectorStoreStatus(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public VectorStoreStatus getValue() {
        return VectorStoreStatus.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link VectorStoreStatus} values.
     *
     * @return The known {@link VectorStoreStatus} values.
     */
    public static Collection<VectorStoreStatus> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link VectorStoreStatus} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link VectorStoreStatus} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static VectorStoreStatus fromString(String name) {
        if (name == null) {
            return null;
        }

        VectorStoreStatus exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, VectorStoreStatus::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof VectorStoreStatus)) {
            return false;
        }

        VectorStoreStatus other = (VectorStoreStatus) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * expired status indicates that this vector store has expired and is no longer available for use.
     */
    
    public static final VectorStoreStatus EXPIRED = fromString("expired");

    /**
     * in_progress status indicates that this vector store is still processing files.
     */
    
    public static final VectorStoreStatus IN_PROGRESS = fromString("in_progress");

    /**
     * completed status indicates that this vector store is ready for use.
     */
    
    public static final VectorStoreStatus COMPLETED = fromString("completed");

}
