// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants.models;


import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Query parameter filter for vector store file retrieval endpoint.
 */
public final class VectorStoreFileStatusFilter implements ExpandableEnum<VectorStoreFileStatusFilter> {
    private static final Map<String, VectorStoreFileStatusFilter> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private VectorStoreFileStatusFilter(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public VectorStoreFileStatusFilter getValue() {
        return VectorStoreFileStatusFilter.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link VectorStoreFileStatusFilter} values.
     *
     * @return The known {@link VectorStoreFileStatusFilter} values.
     */
    public static Collection<VectorStoreFileStatusFilter> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link VectorStoreFileStatusFilter} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link VectorStoreFileStatusFilter} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static VectorStoreFileStatusFilter fromString(String name) {
        if (name == null) {
            return null;
        }

        VectorStoreFileStatusFilter exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, VectorStoreFileStatusFilter::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof VectorStoreFileStatusFilter)) {
            return false;
        }

        VectorStoreFileStatusFilter other = (VectorStoreFileStatusFilter) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }

    /**
     * Retrieve only files that are currently being processed.
     */
    
    public static final VectorStoreFileStatusFilter IN_PROGRESS = fromString("in_progress");

    /**
     * Retrieve only files that have been successfully processed.
     */
    
    public static final VectorStoreFileStatusFilter COMPLETED = fromString("completed");

    /**
     * Retrieve only files that have failed to process.
     */
    
    public static final VectorStoreFileStatusFilter FAILED = fromString("failed");

    /**
     * Retrieve only files that were cancelled.
     */
    
    public static final VectorStoreFileStatusFilter CANCELLED = fromString("cancelled");

  }
