// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.ai.openai.assistants;

import com.azure.ai.openai.assistants.implementation.AssistantsClientServiceImpl;
import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.ServiceClientBuilder;
import io.clientcore.core.credential.KeyCredential;
import io.clientcore.core.http.client.HttpClient;
import io.clientcore.core.http.models.HttpLogOptions;
import io.clientcore.core.http.models.HttpRedirectOptions;
import io.clientcore.core.http.models.HttpRetryOptions;
import io.clientcore.core.http.pipeline.HttpLoggingPolicy;
import io.clientcore.core.http.pipeline.HttpPipeline;
import io.clientcore.core.http.pipeline.HttpPipelineBuilder;
import io.clientcore.core.http.pipeline.HttpPipelinePolicy;
import io.clientcore.core.http.pipeline.HttpRedirectPolicy;
import io.clientcore.core.http.pipeline.HttpRetryPolicy;
import io.clientcore.core.http.pipeline.KeyCredentialPolicy;
import io.clientcore.core.implementation.http.serializer.DefaultJsonSerializer;
import io.clientcore.core.models.traits.ConfigurationTrait;
import io.clientcore.core.models.traits.EndpointTrait;
import io.clientcore.core.models.traits.HttpTrait;
import io.clientcore.core.models.traits.KeyCredentialTrait;
import io.clientcore.core.util.ClientLogger;
import io.clientcore.core.util.configuration.Configuration;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * A builder for creating a new instance of the AssistantsClient type.
 */
@ServiceClientBuilder(serviceClients = {AssistantsClient.class})
public final class AssistantsClientBuilder implements HttpTrait<AssistantsClientBuilder>,
    ConfigurationTrait<AssistantsClientBuilder>,
    KeyCredentialTrait<AssistantsClientBuilder>, EndpointTrait<AssistantsClientBuilder> {


    private static final String SDK_NAME = "name";


    private static final String SDK_VERSION = "version";


    private static final String[] DEFAULT_SCOPES = new String[] {"https://cognitiveservices.azure.com/.default"};


    private final List<HttpPipelinePolicy> pipelinePolicies;

    /**
     * Create an instance of the AssistantsClientBuilder.
     */

    public AssistantsClientBuilder() {
        this.pipelinePolicies = new ArrayList<>();
    }

    /*
     * The HTTP httpPipeline to send requests through.
     */

    private HttpPipeline pipeline;

    /**
     * {@inheritDoc}.
     */

    @Override
    public AssistantsClientBuilder httpPipeline(HttpPipeline pipeline) {
        if (this.pipeline != null && pipeline == null) {
            LOGGER.atInfo().log("HttpPipeline is being set to 'null' when it was previously configured.");
        }
        this.pipeline = pipeline;
        return this;
    }

    /*
     * The HTTP client used to send the request.
     */

    private HttpClient httpClient;

    /**
     * {@inheritDoc}.
     */

    @Override
    public AssistantsClientBuilder httpClient(HttpClient httpClient) {
        this.httpClient = httpClient;
        return this;
    }

    /*
     * The logging configuration for HTTP requests and responses.
     */

    private HttpLogOptions httpLogOptions;

    /**
     * {@inheritDoc}.
     */

    @Override
    public AssistantsClientBuilder httpLogOptions(HttpLogOptions httpLogOptions) {
        this.httpLogOptions = httpLogOptions;
        return this;
    }

    /*
     * The retry options to configure retry policy for failed requests.
     */

    private HttpRetryOptions retryOptions;

    /**
     * {@inheritDoc}.
     */

    public AssistantsClientBuilder httpRetryOptions(HttpRetryOptions retryOptions) {
        this.retryOptions = retryOptions;
        return this;
    }

    /*
     * The redirect options to configure redirect policy
     */
    @Metadata(generated = true)
    private HttpRedirectOptions redirectOptions;

    /**
     * {@inheritDoc}.
     */
    @Metadata(generated = true)
    public AssistantsClientBuilder httpRedirectOptions(HttpRedirectOptions redirectOptions) {
        this.redirectOptions = redirectOptions;
        return this;
    }

    /**
     * {@inheritDoc}.
     */

    public AssistantsClientBuilder addHttpPipelinePolicy(HttpPipelinePolicy customPolicy) {
        Objects.requireNonNull(customPolicy, "'customPolicy' cannot be null.");
        pipelinePolicies.add(customPolicy);
        return this;
    }

    /*
     * The configuration store that is used during construction of the service client.
     */

    private Configuration configuration;

    /**
     * {@inheritDoc}.
     */

    @Override
    public AssistantsClientBuilder configuration(Configuration configuration) {
        this.configuration = configuration;
        return this;
    }

    /*
     * The KeyCredential used for authentication.
     */

    private KeyCredential keyCredential;

    /**
     * {@inheritDoc}.
     */

    @Override
    public AssistantsClientBuilder credential(KeyCredential keyCredential) {
        this.keyCredential = keyCredential;
        return this;
    }

    /*
     * The service endpoint
     */

    private String endpoint;

    /**
     * {@inheritDoc}.
     */

    @Override
    public AssistantsClientBuilder endpoint(String endpoint) {
        this.endpoint = endpoint;
        return this;
    }


    private HttpPipeline createHttpPipeline() {
        Configuration buildConfiguration
            = (configuration == null) ? Configuration.getGlobalConfiguration() : configuration;
        HttpLogOptions localHttpLogOptions = this.httpLogOptions == null ? new HttpLogOptions() : this.httpLogOptions;
        List<HttpPipelinePolicy> policies = new ArrayList<>();
        policies.add(redirectOptions == null ? new HttpRedirectPolicy() : new HttpRedirectPolicy(redirectOptions));
        policies.add(retryOptions == null ? new HttpRetryPolicy() : new HttpRetryPolicy(retryOptions));
        this.pipelinePolicies.stream().forEach(p -> policies.add(p));
        policies.add(new KeyCredentialPolicy("api-key", keyCredential));
        policies.add(new HttpLoggingPolicy(localHttpLogOptions));
        HttpPipeline httpPipeline = new HttpPipelineBuilder().policies(policies.toArray(new HttpPipelinePolicy[0]))
            .httpClient(httpClient)
            .build();
        return httpPipeline;
    }

    private static final ClientLogger LOGGER = new ClientLogger(AssistantsClientBuilder.class);

    /**
     * Builds an instance of AssistantsClient class.
     *
     * @return an instance of AssistantsClient.
     */

    public AssistantsClient buildClient() {
        return new AssistantsClient(buildInnerClient());
    }

    /*
     * Service version
     */

    private AssistantsServiceVersion serviceVersion;

    /**
     * Sets Service version.
     *
     * @param serviceVersion the serviceVersion value.
     *
     * @return the AssistantsClientBuilder.
     */

    public AssistantsClientBuilder serviceVersion(AssistantsServiceVersion serviceVersion) {
        this.serviceVersion = serviceVersion;
        return this;
    }

    /**
     * Builds an instance of AssistantsClientServiceImpl with the provided parameters.
     *
     * @return an instance of AssistantsClientServiceImpl.
     */
    private AssistantsClientServiceImpl buildInnerClient() {
        HttpPipeline localPipeline = (pipeline != null) ? pipeline : createHttpPipeline();
        AssistantsServiceVersion localServiceVersion
            = (serviceVersion != null) ? serviceVersion : AssistantsServiceVersion.getLatest();
        return new AssistantsClientServiceImpl(localPipeline, new DefaultJsonSerializer(),
        this.endpoint + (this.endpoint.endsWith("/") ? "openai" : "/openai"),
        localServiceVersion);
    }
}
