// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.service.clientlibrary.models;

import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Defines the possible descriptors for available audio operation responses.
 */
public final class AudioTaskLabel implements ExpandableEnum<AudioTaskLabel> {

    private static final Map<String, AudioTaskLabel> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private AudioTaskLabel(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public AudioTaskLabel getValue() {
        return AudioTaskLabel.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link AudioTaskLabel} values.
     *
     * @return The known {@link AudioTaskLabel} values.
     */
    public static Collection<AudioTaskLabel> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link AudioTaskLabel} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link AudioTaskLabel} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static AudioTaskLabel fromString(String name) {
        if (name == null) {
            return null;
        }

        AudioTaskLabel exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, AudioTaskLabel::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof AudioTaskLabel)) {
            return false;
        }

        AudioTaskLabel other = (AudioTaskLabel) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }
    
    /**
     * Accompanying response data resulted from an audio transcription task.
     */
    
    public static final AudioTaskLabel TRANSCRIBE = fromString("transcribe");

    /**
     * Accompanying response data resulted from an audio translation task.
     */
    
    public static final AudioTaskLabel TRANSLATE = fromString("translate");
}
