// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.service.clientlibrary.models;

import io.clientcore.core.util.ExpandableEnum;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Defines available options for the underlying response format of output transcription information.
 */
public final class AudioTranscriptionFormat implements ExpandableEnum<AudioTranscriptionFormat> {
    private static final Map<String, AudioTranscriptionFormat> VALUES = new ConcurrentHashMap<>();

    private final String caseSensitive;
    private final String caseInsensitive;

    private AudioTranscriptionFormat(String name) {
        this.caseSensitive = name;
        this.caseInsensitive = name.toLowerCase();
    }

    @Override
    public AudioTranscriptionFormat getValue() {
        return AudioTranscriptionFormat.fromString(caseSensitive);
    }

    /**
     * Gets all known {@link AudioTranscriptionFormat} values.
     *
     * @return The known {@link AudioTranscriptionFormat} values.
     */
    public static Collection<AudioTranscriptionFormat> values() {
        return VALUES.values();
    }

    /**
     * Creates or finds a {@link AudioTranscriptionFormat} for the passed {@code name}.
     *
     * <p>{@code null} will be returned if {@code name} is {@code null}.</p>
     *
     * @param name A name to look for.
     *
     * @return The corresponding {@link AudioTranscriptionFormat} of the provided name, or {@code null} if {@code name} was
     * {@code null}.
     */
    public static AudioTranscriptionFormat fromString(String name) {
        if (name == null) {
            return null;
        }

        AudioTranscriptionFormat exceptionType = VALUES.get(name);

        if (exceptionType != null) {
            return exceptionType;
        }

        return VALUES.computeIfAbsent(name, AudioTranscriptionFormat::new);
    }

    @Override
    public String toString() {
        return caseSensitive;
    }

    @Override
    public int hashCode() {
        return caseInsensitive.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof AudioTranscriptionFormat)) {
            return false;
        }

        AudioTranscriptionFormat other = (AudioTranscriptionFormat) obj;

        return Objects.equals(caseInsensitive, other.caseInsensitive);
    }
    
    /**
     * Use a response body that is a JSON object containing a single 'text' field for the transcription.
     */
    
    public static final AudioTranscriptionFormat JSON = fromString("json");

    /**
     * Use a response body that is a JSON object containing transcription text along with timing, segments, and other
     * metadata.
     */
    
    public static final AudioTranscriptionFormat VERBOSE_JSON = fromString("verbose_json");

    /**
     * Use a response body that is plain text containing the raw, unannotated transcription.
     */
    
    public static final AudioTranscriptionFormat TEXT = fromString("text");

    /**
     * Use a response body that is plain text in SubRip (SRT) format that also includes timing information.
     */
    
    public static final AudioTranscriptionFormat SRT = fromString("srt");

    /**
     * Use a response body that is plain text in Web Video Text Tracks (VTT) format that also includes timing
     * information.
     */
    
    public static final AudioTranscriptionFormat VTT = fromString("vtt");
}
