// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.service.clientlibrary.implementation;

import com.service.clientlibrary.models.TodoItemPatch;

/**
 * This is the Helper class to enable json merge patch serialization for a model.
 */
public class JsonMergePatchHelper {
    private static TodoItemPatchAccessor todoItemPatchAccessor;

    public interface TodoItemPatchAccessor {
        TodoItemPatch prepareModelForJsonMergePatch(TodoItemPatch todoItemPatch, boolean jsonMergePatchEnabled);
    }

    public static void setTodoItemPatchAccessor(TodoItemPatchAccessor accessor) {
        todoItemPatchAccessor = accessor;
    }

    public static TodoItemPatchAccessor getTodoItemPatchAccessor() {
        return todoItemPatchAccessor;
    }
}
